name: Export Repository Variables

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  export-env-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create .env file with repository variables
        run: |
          echo "EXPO_PUBLIC_USER_POOL_ID_BETA=${{ vars.EXPO_PUBLIC_USER_POOL_ID_BETA }}" >> .env
          echo "EXPO_PUBLIC_WEB_CLIENT_ID_BETA=${{ vars.EXPO_PUBLIC_WEB_CLIENT_ID_BETA }}" >> .env
          echo "EXPO_PUBLIC_COGNITO_DOMAIN_BETA=${{ vars.EXPO_PUBLIC_COGNITO_DOMAIN_BETA }}" >> .env
          echo "EXPO_PUBLIC_IDENTITY_POOL_ID_BETA=${{ vars.EXPO_PUBLIC_IDENTITY_POOL_ID_BETA }}" >> .env

          echo "EXPO_PUBLIC_USER_POOL_ID_PROD=${{ vars.EXPO_PUBLIC_USER_POOL_ID_PROD }}" >> .env
          echo "EXPO_PUBLIC_WEB_CLIENT_ID_PROD=${{ vars.EXPO_PUBLIC_WEB_CLIENT_ID_PROD }}" >> .env
          echo "EXPO_PUBLIC_COGNITO_DOMAIN_PROD=${{ vars.EXPO_PUBLIC_COGNITO_DOMAIN_PROD }}" >> .env
          echo "EXPO_PUBLIC_IDENTITY_POOL_ID_PROD=${{ vars.EXPO_PUBLIC_IDENTITY_POOL_ID_PROD }}" >> .env

          echo "EXPO_PUBLIC_AWS_REGION=${{ vars.EXPO_PUBLIC_AWS_REGION }}" >> .env

      - name: Upload .env file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: env-file
          path: .env
